import * as React from 'react';
import {StyledTextField,StyledBox,StyledAutocomplete} from './StyledComponents'


export default function CountrySelection({ value, setValue }) {
  return (
    <StyledAutocomplete
      value={value}
      onChange={(event, newValue) => setValue(event, newValue)}
      size='small'
      id="Nationality-Select"
      options={countries.sort((a, b) => -b.label.localeCompare(a.label))} fullWidth
      // {countries.sort((a, b) => -b.firstLetter.localeCompare(a.firstLetter))}
      autoHighlight
      getOptionLabel={(option) => option.label}
      renderOption={(props, option) => (
        <StyledBox component="li" sx={{ '& > img': { mr: 2, flexShrink: 0, } }} {...props}>
        { option.label !==' All' &&  <img
            loading="lazy"
            width="20"
            src={`https://flagcdn.com/w20/${option.code.toLowerCase()}.png`}
            srcSet={`https://flagcdn.com/w40/${option.code.toLowerCase()}.png 2x`}
            alt={option.code}
            // alt=''
          />}
          {option.label}
        </StyledBox>
      )}
      renderInput={(params) => (
        <StyledTextField
          {...params}
          inputProps={{
            ...params.inputProps,
            autoComplete: 'new-password',
          }}
        />
      )}
    />
  );
}


const countries = [
  { code: "All", tag: "All", label: " All" },
  { code: "AD", tag: "AND", label: "Andorra" },
  { code: "AF", tag: "AFG", label: "Afghanistan" },
  { code: "AG", tag: "ATG", label: "Antigua and Barbuda" },
  { code: "AI", tag: "AIA", label: "Anguilla" },
  { code: "AL", tag: "ALB", label: "Albania" },
  { code: "AM", tag: "ARM", label: "Armenia" },
  { code: "AO", tag: "AGO", label: "Angola" },
  { code: "AQ", tag: "ATA", label: "Antarctica" },
  { code: "AR", tag: "ARG", label: "Argentina" },
  { code: "AS", tag: "ASM", label: "American Samoa" },
  { code: "AT", tag: "AUT", label: "Austria" },
  { code: "AU", tag: "AUS", label: "Australia" },
  { code: "AW", tag: "ABW", label: "Aruba" },
  { code: "AX", tag: "ALA", label: "Alland Islands" },
  { code: "AZ", tag: "AZE", label: "Azerbaijan" },
  { code: "BA", tag: "BIH", label: "Bosnia and Herzegovina" },
  { code: "BB", tag: "BRB", label: "Barbados" },
  { code: "BD", tag: "BGD", label: "Bangladesh" },
  { code: "BE", tag: "BEL", label: "Belgium" },
  { code: "BF", tag: "BFA", label: "Burkina Faso" },
  { code: "BG", tag: "BGR", label: "Bulgaria" },
  { code: "BH", tag: "BHR", label: "Bahrain" },
  { code: "BI", tag: "BDI", label: "Burundi" },
  { code: "BJ", tag: "BEN", label: "Benin" },
  { code: "BL", tag: "BLM", label: "Saint Barthelemy" },
  { code: "BM", tag: "BMU", label: "Bermuda" },
  { code: "BN", tag: "BRN", label: "Brunei Darussalam" },
  { code: "BO", tag: "BOL", label: "Bolivia" },
  { code: "BR", tag: "BRA", label: "Brazil" },
  { code: "BS", tag: "BHS", label: "Bahamas" },
  { code: "BT", tag: "BTN", label: "Bhutan" },
  { code: "BV", tag: "BVT", label: "Bouvet Island" },
  { code: "BW", tag: "BWA", label: "Botswana" },
  { code: "BY", tag: "BLR", label: "Belarus" },
  { code: "BZ", tag: "BLZ", label: "Belize" },
  { code: "CA", tag: "CAN", label: "Canada" },
  { code: "CC", tag: "CCK", label: "Cocos (Keeling) Islands" },
  { code: "CD", tag: "COG", label: "Congo, Democratic Republic of the" },
  { code: "CF", tag: "CAF", label: "Central African Republic" },
  { code: "CG", tag: "COD", label: "Congo, Republic of the" },
  { code: "CH", tag: "CHE", label: "Switzerland" },
  { code: "CI", tag: "CIV", label: "Cote d'Ivoire" },
  { code: "CK", tag: "COK", label: "Cook Islands" },
  { code: "CL", tag: "CHL", label: "Chile" },
  { code: "CM", tag: "CMR", label: "Cameroon" },
  { code: "CN", tag: "CHN", label: "China" },
  { code: "CO", tag: "COL", label: "Colombia" },
  { code: "CR", tag: "CRI", label: "Costa Rica" },
  { code: "CU", tag: "CUB", label: "Cuba" },
  { code: "CV", tag: "CPV", label: "Cape Verde" },
  { code: "CW", tag: "CUW", label: "Curacao" },
  { code: "CX", tag: "CXR", label: "Christmas Island" },
  { code: "CY", tag: "CZP", label: "Cyprus" },
  { code: "CZ", tag: "CZE", label: "Czech Republic" },
  { code: "DE", tag: "DEU", label: "Germany" },
  { code: "DJ", tag: "DJI", label: "Djibouti" },
  { code: "DK", tag: "DNK", label: "Denmark" },
  { code: "DM", tag: "DMA", label: "Dominica" },
  { code: "DO", tag: "DOM", label: "Dominican Republic" },
  { code: "DZ", tag: "DZA", label: "Algeria" },
  { code: "EC", tag: "ECO", label: "Ecuador" },
  { code: "EE", tag: "EST", label: "Estonia" },
  { code: "EG", tag: "EGY", label: "Egypt" },
  { code: "EH", tag: "ESH", label: "Western Sahara" },
  { code: "ER", tag: "ERI", label: "Eritrea" },
  { code: "ES", tag: "ESP", label: "Spain" },
  { code: "ET", tag: "ETH", label: "Ethiopia" },
  { code: "FI", tag: "FIN", label: "Finland" },
  { code: "FJ", tag: "FJI", label: "Fiji" },
  { code: "FK", tag: "FLK", label: "Falkland Islands (Malvinas)" },
  { code: "FM", tag: "FSM", label: "Micronesia, Federated States of" },
  { code: "FO", tag: "FRO", label: "Faroe Islands" },
  { code: "FR", tag: "FRA", label: "France" },
  { code: "GA", tag: "GAB", label: "Gabon" },
  { code: "GB", tag: "GBR", label: "United Kingdom" },
  { code: "GD", tag: "GRD", label: "Grenada" },
  { code: "GE", tag: "GEO", label: "Georgia" },
  { code: "GF", tag: "GUF", label: "French Guiana" },
  { code: "GG", tag: "GGY", label: "Guernsey" },
  { code: "GH", tag: "GHA", label: "Ghana" },
  { code: "GI", tag: "GIB", label: "Gibraltar" },
  { code: "GL", tag: "GRL", label: "Greenland" },
  { code: "GM", tag: "GMB", label: "Gambia" },
  { code: "GN", tag: "GIN", label: "Guinea" },
  { code: "GP", tag: "GLP", label: "Guadeloupe" },
  { code: "GQ", tag: "GNQ", label: "Equatorial Guinea" },
  { code: "GR", tag: "GRC", label: "Greece" },
  { code: "GS", tag: "SGS", label: "South Georgia and the South Sandwich Islands" },
  { code: "GT", tag: "GTM", label: "Guatemala" },
  { code: "GU", tag: "GUM", label: "Guam" },
  { code: "GW", tag: "GNB", label: "Guinea-Bissau" },
  { code: "GY", tag: "GUY", label: "Guyana" },
  { code: "HK", tag: "HKG", label: "Hong Kong" },
  { code: "HM", tag: "HMD", label: "Heard Island and McDonald Islands" },
  { code: "HN", tag: "HND", label: "Honduras" },
  { code: "HR", tag: "HRV", label: "Croatia" },
  { code: "HT", tag: "HTI", label: "Haiti" },
  { code: "HU", tag: "HUN", label: "Hungary" },
  { code: "ID", tag: "IDN", label: "Indonesia" },
  { code: "IE", tag: "IRL", label: "Ireland" },
  { code: "IL", tag: "ISR", label: "Israel" },
  { code: "IM", tag: "IMN", label: "Isle of Man" },
  { code: "IN", tag: "IND", label: "India" },
  { code: "IO", tag: "IOT", label: "British Indian Ocean Territory" },
  { code: "IQ", tag: "IRQ", label: "Iraq" },
  { code: "IR", tag: "IRN", label: "Iran, Islamic Republic of" },
  { code: "IS", tag: "ISL", label: "Iceland" },
  { code: "IT", tag: "ITA", label: "Italy" },
  { code: "JE", tag: "JEY", label: "Jersey" },
  { code: "JM", tag: "JAM", label: "Jamaica" },
  { code: "JO", tag: "JOR", label: "Jordan" },
  { code: "JP", tag: "JPN", label: "Japan" },
  { code: "KE", tag: "KEN", label: "Kenya" },
  { code: "KG", tag: "KGZ", label: "Kyrgyzstan" },
  { code: "KH", tag: "KHM", label: "Cambodia" },
  { code: "KI", tag: "KIR", label: "Kiribati" },
  { code: "KM", tag: "COM", label: "Comoros" },
  { code: "KN", tag: "KNA", label: "Saint Kitts and Nevis" },
  { code: "KP", tag: "KOR", label: "Korea, Democratic People's Republic of South" },
  { code: "KR", tag: "PRK", label: "Korea, Republic of North" },
  { code: "KW", tag: "KWT", label: "Kuwait" },
  { code: "KY", tag: "CYM", label: "Cayman Islands" },
  { code: "KZ", tag: "KAZ", label: "Kazakhstan" },
  { code: "LA", tag: "LAO", label: "Lao People's Democratic Republic" },
  { code: "LB", tag: "LBN", label: "Lebanon" },
  { code: "LC", tag: "All", label: "Saint Lucia" },
  { code: "LI", tag: "LIE", label: "Liechtenstein" },
  { code: "LK", tag: "LKA", label: "Sri Lanka" },
  { code: "LR", tag: "LBR", label: "Liberia" },
  { code: "LS", tag: "LSO", label: "Lesotho" },
  { code: "LT", tag: "LTU", label: "Lithuania" },
  { code: "LU", tag: "LUX", label: "Luxembourg" },
  { code: "LV", tag: "LVA", label: "Latvia" },
  { code: "LY", tag: "LBY", label: "Libya" },
  { code: "MA", tag: "MAR", label: "Morocco" },
  { code: "MC", tag: "MCO", label: "Monaco" },
  { code: "MD", tag: "MDA", label: "Moldova, Republic of" },
  { code: "ME", tag: "MNE", label: "Montenegro" },
  { code: "MF", tag: "MAF", label: "Saint Martin (French part)" },
  { code: "MG", tag: "MDG", label: "Madagascar" },
  { code: "MH", tag: "MHL", label: "Marshall Islands" },
  { code: "MK", tag: "MKD", label: "Macedonia, the Former Yugoslav Republic of" },
  { code: "ML", tag: "MLI", label: "Mali" },
  { code: "MM", tag: "MMR", label: "Myanmar" },
  { code: "MN", tag: "MNG", label: "Mongolia" },
  { code: "MO", tag: "MAC", label: "Macao" },
  { code: "MP", tag: "MNP", label: "Northern Mariana Islands" },
  { code: "MQ", tag: "MTQ", label: "Martinique" },
  { code: "MR", tag: "MRT", label: "Mauritania" },
  { code: "MS", tag: "MSR", label: "Montserrat" },
  { code: "MT", tag: "MLT", label: "Malta" },
  { code: "MU", tag: "MUS", label: "Mauritius" },
  { code: "MV", tag: "MDV", label: "Maldives" },
  { code: "MW", tag: "MWI", label: "Malawi" },
  { code: "MX", tag: "MEX", label: "Mexico" },
  { code: "MY", tag: "MYS", label: "Malaysia" },
  { code: "MZ", tag: "MOZ", label: "Mozambique" },
  { code: "NA", tag: "NAM", label: "Namibia" },
  { code: "NC", tag: "NCL", label: "New Caledonia" },
  { code: "NE", tag: "NER", label: "Niger" },
  { code: "NF", tag: "NFK", label: "Norfolk Island" },
  { code: "NG", tag: "NGA", label: "Nigeria" },
  { code: "NI", tag: "NIC", label: "Nicaragua" },
  { code: "NL", tag: "NLD", label: "Netherlands" },
  { code: "NO", tag: "NOR", label: "Norway" },
  { code: "NP", tag: "NPL", label: "Nepal" },
  { code: "NR", tag: "NRU", label: "Nauru" },
  { code: "NU", tag: "NIU", label: "Niue" },
  { code: "NZ", tag: "NZL", label: "New Zealand" },
  { code: "OM", tag: "OMN", label: "Oman" },
  { code: "PA", tag: "PAN", label: "Panama" },
  { code: "PE", tag: "PER", label: "Peru" },
  { code: "PF", tag: "PYF", label: "French Polynesia" },
  { code: "PG", tag: "PNG", label: "Papua New Guinea" },
  { code: "PH", tag: "PHL", label: "Philippines" },
  { code: "PK", tag: "PAK", label: "Pakistan" },
  { code: "PL", tag: "POL", label: "Poland" },
  { code: "PM", tag: "SPM", label: "Saint Pierre and Miquelon" },
  { code: "PN", tag: "PCN", label: "Pitcairn" },
  { code: "PR", tag: "PRI", label: "Puerto Rico" },
  { code: "PS", tag: "PSE", label: "Palestine, State of" },
  { code: "PT", tag: "PRT", label: "Portugal" },
  { code: "PW", tag: "PLW", label: "Palau" },
  { code: "PY", tag: "PRY", label: "Paraguay" },
  { code: "QA", tag: "QAT", label: "Qatar" },
  { code: "RE", tag: "REU", label: "Reunion" },
  { code: "RO", tag: "ROU", label: "Romania" },
  { code: "RS", tag: "SRB", label: "Serbia" },
  { code: "RU", tag: "RUS", label: "Russian Federation" },
  { code: "RW", tag: "RWA", label: "Rwanda" },
  { code: "SA", tag: "SAU", label: "Saudi Arabia" },
  { code: "SB", tag: "SLB", label: "Solomon Islands" },
  { code: "SC", tag: "SYC", label: "Seychelles" },
  { code: "SD", tag: "SDN", label: "Sudan" },
  { code: "SE", tag: "SWE", label: "Sweden" },
  { code: "SG", tag: "SGP", label: "Singapore" },
  { code: "SH", tag: "SHN", label: "Saint Helena" },
  { code: "SI", tag: "SVN", label: "Slovenia" },
  { code: "SJ", tag: "SJM", label: "Svalbard and Jan Mayen" },
  { code: "SK", tag: "SVK", label: "Slovakia" },
  { code: "SL", tag: "SLE", label: "Sierra Leone" },
  { code: "SM", tag: "SMR", label: "San Marino" },
  { code: "SN", tag: "SEN", label: "Senegal" },
  { code: "SO", tag: "SOM", label: "Somalia" },
  { code: "SR", tag: "SUR", label: "Suriname" },
  { code: "SS", tag: "SSD", label: "South Sudan" },
  { code: "ST", tag: "STP", label: "Sao Tome and Principe" },
  { code: "SV", tag: "SLV", label: "El Salvador" },
  { code: "SY", tag: "SYR", label: "Syrian Arab Republic" },
  { code: "SZ", tag: "SWZ", label: "Swaziland" },
  { code: "TC", tag: "TCA", label: "Turks and Caicos Islands" },
  { code: "TD", tag: "TCD ", label: "Chad" },
  { code: "TF", tag: "ATF", label: "French Southern Territories" },
  { code: "TG", tag: "TGO", label: "Togo" },
  { code: "TH", tag: "THA", label: "Thailand" },
  { code: "TJ", tag: "TJK ", label: "Tajikistan" },
  { code: "TK", tag: "TKL", label: "Tokelau" },
  { code: "TL", tag: "TLS", label: "Timor-Leste" },
  { code: "TM", tag: "TKM", label: "Turkmenistan" },
  { code: "TN", tag: "TUN", label: "Tunisia" },
  { code: "TO", tag: "TON", label: "Tonga" },
  { code: "TR", tag: "TUR", label: "Turkey" },
  { code: "TT", tag: "TTO", label: "Trinidad and Tobago" },
  { code: "TV", tag: "TUV", label: "Tuvalu" },
  { code: "TW", tag: "TWN", label: "Taiwan, Republic of China" },
  { code: "TZ", tag: "TZA", label: "United Republic of Tanzania" },
  { code: "UA", tag: "UKR", label: "Ukraine" },
  { code: "UG", tag: "UGA", label: "Uganda" },
  { code: "AE", tag: "ARE", label: "United Arab Emirates" },
  { code: "US", tag: "USA", label: "United States" },
  { code: "UY", tag: "URY", label: "Uruguay" },
  { code: "UZ", tag: "UZB", label: "Uzbekistan" },
  { code: "VA", tag: "VAT", label: "Holy See (Vatican City State)" },
  { code: "VC", tag: "VCT", label: "Saint Vincent and the Grenadines" },
  { code: "VE", tag: "VEN", label: "Venezuela" },
  { code: "VG", tag: "VGB", label: "British Virgin Islands" },
  { code: "VI", tag: "VIR", label: "US Virgin Islands" },
  { code: "VN", tag: "VNM", label: "Vietnam" },
  { code: "VU", tag: "VUT", label: "Vanuatu" },
  { code: "WF", tag: "WLF", label: "Wallis and Futuna" },
  { code: "WS", tag: "WSM", label: "Samoa" },
  { code: "XK", tag: "KSV", label: "Kosovo" },
  { code: "YE", tag: "YEM", label: "Yemen" },
  { code: "YT", tag: "MYT", label: "Mayotte" },
  { code: "ZA", tag: "ZAF", label: "South Africa" },
  { code: "ZM", tag: "ZMB", label: "Zambia" },
  { code: "ZW", tag: "ZWE", label: "Zimbabwe" },
];
